-- Create the euk schema
CREATE SCHEMA IF NOT EXISTS "euk";

-- Grant permissions to the schema
GRANT ALL ON SCHEMA "euk" TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "euk" TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "euk" TO PUBLIC;

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA "euk" GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA "euk" GRANT ALL ON SEQUENCES TO PUBLIC;
