version: '3.8'

services:
  sirus-backend:
    image: sirus-backend:latest
    container_name: sirus-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres
      - DATABASE_USERNAME=postgres.wynfrojhkzddzjbrpdcr
      - DATABASE_PASSWORD=a*Xxk3B7?HF8&3r
      - JWT_SECRET=moj-super-tajan-jwt-kljuc-za-sirus-aplikaciju-20244
      - JWT_EXPIRATION=86400000
      - ADMIN_PASSWORD=moja-admin-lozinka123
      - EUK_ALLOWED_DOMAINS=http://localhost:3000,https://euk.vercel.app
      - EUK_RATE_LIMIT_ENABLED=true
      - EUK_RATE_LIMIT_MAX_REQUESTS=150
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/test/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
